function plot_detection(zz,param)
% plot_detection(z,zz,param,bad_indice)
%
% z: the rank 1 approximation of the result of our algorithm
% zz: is the rough rounding of zz in the {0,1} space (which is equivalent
% to {-1,1} space with a translation.
% param is the structure containing all our parameters (generated by
% parameter.m)
% bad_indice is a tab containing the id of the empty superpixels 


fprintf('plotting....')

%% LOAD SUPERPIXELS

[~,lW,bad_indice]=chunk_norris(param);

[~, all_position,lW_sp,~,~] = open_superpix(param);

bad_indice(bad_indice>sum(lW_sp(1:param.pic.np_considered)))    = [];
all_position(bad_indice,:)                                      = [];


try   
    plot_groups(param,all_position,zz,lW,2,100,bad_indice);
catch
    fprintf('[plot_detection] error plotting results\n')
    keyboard
end



fprintf('done\n')